name: ice
description: ZeroC Ice implement in Dart.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  uuid: 3.0.4
  args: 2.3.0
  meta: 1.7.0

dev_dependencies:
  pedantic: 1.11.1
  test: 1.17.12
