name: slice
version: 0.0.1
description: Ice Slice file parser and tool to generate dart code
homepage: https://github.com/pedia/dart-ice/tree/master/slice

environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  meta: ^1.0.2
  args: 2.3.0
  path: 1.8.0

dev_dependencies:
  test: ^1.3.4
  ice:
    path: ../ice